global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nifi"
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["nifi:8443"]
        labels:
          instance: "nifi-primary"

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9101"]
        labels:
          instance: "kafka-broker-1"

  - job_name: "timescaledb"
    static_configs:
      - targets: ["timescaledb:9187"]
        labels:
          instance: "timescaledb"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
